### ISSUE TITLE
won't build with Ivy 2.5

### ISSUE THREAD

**Issue by lhoekenga** [robertogallea/jaas_relational_login#4]
I tried to rebuild jaas_relational_login recently.  ivy 2.3.0 generatings "http" urls for the dependencies instead of "https", as does ivy 2.4.0

So.. I tried updating to ivy 2.5.0, and while it downloads the dependencies in the lib directory, it doesn't use them when it tries to build the target jar:

 ```
compile:
    [echo] compiling...
    [javac] Compiling 6 source files to /home/liamr/git/jaas_relational_login/target/classes
    [javac] /home/liamr/git/jaas_relational_login/src/relationalLogin/DBLogin.java:14: error: package org.springframework.security.crypto.password does not exist
    [javac] import org.springframework.security.crypto.password.PasswordEncoder;
    [javac]                                                    ^
    [javac] /home/liamr/git/jaas_relational_login/src/relationalLogin/DBLogin.java:15: error: package org.springframework.security.crypto.bcrypt does not exist
    [javac] import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
    [javac]                                                  ^
    [javac] /home/liamr/git/jaas_relational_login/src/relationalLogin/DBLogin.java:16: error: package org.apache.commons.codec.digest does not exist
    [javac] import org.apache.commons.codec.digest.Md5Crypt;
    [javac]                                       ^
    [javac] /home/liamr/git/jaas_relational_login/src/relationalLogin/DBLogin.java:36: error: cannot find symbol
    [javac] 	private PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
    [javac] 	        ^
    [javac]   symbol:   class PasswordEncoder
    [javac]   location: class DBLogin
    [javac] /home/liamr/git/jaas_relational_login/src/relationalLogin/DBLogin.java:36: error: cannot find symbol
    [javac] 	private PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
    [javac] 	                                              ^
    [javac]   symbol:   class BCryptPasswordEncoder
    [javac]   location: class DBLogin
    [javac] /home/liamr/git/jaas_relational_login/src/relationalLogin/DBLogin.java:76: error: cannot find symbol
    [javac] 					if (!upwd.equals(Md5Crypt.md5Crypt(tpwd.getBytes(), upwd))) throw new FailedLoginException(getOption("errorMessage", "Invalid details"));
    [javac] 					                 ^
    [javac]   symbol:   variable Md5Crypt
    [javac]   location: class DBLogin
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 6 errors

BUILD FAILED
/home/liamr/git/jaas_relational_login/build.xml:30: Compile failed; see the compiler error output for details.
```

**Comment by lhoekenga** [comment]
#5 updates to build.xml to for ivy 2.5.0, new maven hostname, and a compile time classpath
